### ISSUE TITLE
Not working with Tailwind 2.1 using JIT

### ISSUE THREAD

**Issue by catgofire** [jorenvanhee/tailwindcss-debug-screens#10]
This stopped displaying for me after upgrading Tailwind to 2.1 and enabling the new JIT compiler with `mode: 'jit'` in tailwind.config.js (*super* speedy, can't believe I ever lived without it). I haven't tried to fix it or look into the issue at all — I'll update here if I figure it out. I was just hoping someone else had experienced this and fixed it somehow 😁

**Comment by froeb** [comment]
I have the same issue

**Comment by jorenvanhee** [comment]
Is the class `debug-screens` available as a string in one of your template files present in the purge config?

```
purge: [
  './public/**/*.html',
  './src/**/*.{js,jsx,ts,tsx,vue}',
],
```

**Comment by catgofire** [comment]
@jorenvanhee Turns out it was not! I use https://github.com/roots/sage, and in `index.php` at the top level of the theme directory I have 

```php
<body <?php body_class(env('WP_ENV') === 'development' ? 'debug-screens' : ''); ?>>
```

I added "index.php" to my tailwind config and debug-screens is showing up again. Thank you!

```js
  purge: {
    content: [
      './app/**/*.php',
      './resources/**/*.{php,vue,js}',
      'index.php',
    ],
```

**Comment by jhirn** [comment]
Had a similar head scratcher with Rails switching from erb to slim. Needed to add     '`./app/views/**/*.html.{slim,erb}*'` to my views. 

I love this plugin so much it was painful when it went away.
