### ISSUE TITLE
bug when Customing media queries

### ISSUE THREAD

**Issue by scil** [jorenvanhee/tailwindcss-debug-screens#14]
I add a new breakpoint  `lgg` between `lg` and `xl`. then  this plugin can recognize  `lgg`, but not   `xl`. 

even screen width is far more than `xl`, it still shows `lgg`

tailwind.config.css
```
  theme: {
    
    extend: {
    
      screens: {
        // lg < lgg < xl
        // lg: 1024
        // xl: 1280
        lgg: '1125px',
      },
    },
  },


```

**Comment by scil** [comment]
the cause is the produced css
```

@media (min-width: 1280px) {
  .debug-screens::before {
    content: 'screen: xl';
  }
}

@media (min-width: 1125px) {
  .debug-screens::before {
    content: 'screen: lgg';
  }
}
```


the css code did not changed even I add `xl` under `lgg`
```
      screens: {
        lgg: '1125px',
        xl: '1280px',
      },
```

or  override the whole default config

```
theme: {

    screens: {
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',

      'lgg': '1125px',   

      'xl': '1280px',

       },
}
```

**Comment by scil** [comment]
my temp sollution

add this to site css file
```

@media (min-width: 1280px) {
    .debug-screens::before {
        content: 'screen: xl' !important;
    }
}
```

**Comment by jorenvanhee** [comment]
I tried to replicate it on [Tailwind Play](https://play.tailwindcss.com/9ew932qCZk?file=config) and it works just fine. Can you reproduce it on Tailwind Play?

**Comment by scil** [comment]
> I tried to replicate it on [Tailwind Play](https://play.tailwindcss.com/9ew932qCZk?file=config) and it works just fine. Can you reproduce it on Tailwind Play?

Thank you.

I use Tailwind v1.
