### ISSUE TITLE
Support for multiple breakpoint which does make sense.

### ISSUE THREAD

**Issue by Kcko** [jorenvanhee/tailwindcss-debug-screens#15]
This is extended configuration for breakpoints

```
    screens: {
      smd: { max: '639px' },
      sm: '640px',
      mdd: { max: '767px' },
      md: '768px',
      lgd: { max: '1023px' },
      lg: '1024px',
      xld: { max: '1279px' },
      xl: '1280px',
      xxld: { max: '1535px' },
      xxl: '1536px',
      '4kd': { max: '1920px' },
      '4k': '1921px'
    },
```

But i always see **4kd** ;-) , is any way how to update this plugin  proper behavior?

**Comment by jorenvanhee** [comment]
In your case I would add all the breakpoints with `max` to the ignore option of the plugin. Does this work for you?

```
module.exports = {
  theme: {
    screens: {
      smd: { max: '639px' },
      sm: '640px',
      mdd: { max: '767px' },
      md: '768px',
      lgd: { max: '1023px' },
      lg: '1024px',
      xld: { max: '1279px' },
      xl: '1280px',
      xxld: { max: '1535px' },
      xxl: '1536px',
      '4kd': { max: '1920px' },
      '4k': '1921px',
    },
    debugScreens: {
      ignore: ['4kd', 'xxld', 'xld', 'lgd', 'mdd', 'smd'],
    },
  },
  plugins: [require('tailwindcss-debug-screens')],
}
```

[Example](https://play.tailwindcss.com/TwnkYyqz1B?file=config) on Tailwind Play

**Comment by Kcko** [comment]
> In your case I would add all the breakpoints with `max` to the ignore option of the plugin. Does this work for you?
> 
> ```
> module.exports = {
>   theme: {
>     screens: {
>       smd: { max: '639px' },
>       sm: '640px',
>       mdd: { max: '767px' },
>       md: '768px',
>       lgd: { max: '1023px' },
>       lg: '1024px',
>       xld: { max: '1279px' },
>       xl: '1280px',
>       xxld: { max: '1535px' },
>       xxl: '1536px',
>       '4kd': { max: '1920px' },
>       '4k': '1921px',
>     },
>     debugScreens: {
>       ignore: ['4kd', 'xxld', 'xld', 'lgd', 'mdd', 'smd'],
>     },
>   },
>   plugins: [require('tailwindcss-debug-screens')],
> }
> ```
> 
> [Example](https://play.tailwindcss.com/TwnkYyqz1B?file=config) on Tailwind Play

Hi, thx for anwer.

Seems that does not work as your code looks like.

I see standard BP but not (with "d" postfix) https://bit.ly/3fntrMR

**Comment by jorenvanhee** [comment]
I'm afraid that's one of the limitations of this plugin, it can not show two active breakpoints at the same time. Either you configure it to only show the min-width breakpoints, or the max-width ones. If you need an example to only show the max-width breakpoints, happy to help.
