### ISSUE TITLE
Not updating screen size correctly using Tailwind v 3.2.0

### ISSUE THREAD

**Issue by AhmadYousif89** [jorenvanhee/tailwindcss-debug-screens#16]
I have extended my tw screens to be like :
```
extend: {
      screens: {
        xs: '570px',
        md: '640px',
      },
    },
plugins: [require('tailwindcss-debug-screens')],
```
but now it's doesn't update the screen sizes correctly when resizing, instead it always showing ( screen: xs ) or ( screen:_ ) if the window width is under the xs size = 570px and not even showing the md size!

**Comment by AhmadYousif89** [comment]
oh, I just revisited tailwind docs for customizing screens and I found out that I was doing it wrong 😅
it turns out that I need to do this instead :
```
const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
  theme: {
    screens: {
      xs: '570px',
      md: '640px',
      ...defaultTheme.screens,
    },
  },
  plugins: [require('tailwindcss-debug-screens')],
}
```
my bad 😅

**Comment by jorenvanhee** [comment]
Glad you figured it out :)
