### ISSUE TITLE
Tooltip shows the wrong screen size

### ISSUE THREAD

**Issue by nikoisonfire** [jorenvanhee/tailwindcss-debug-screens#17]
Anything smaller than md (which should be larger than only a few pixels while resizing) is shown as lg-max

![image](https://user-images.githubusercontent.com/22169321/234031882-c77c8288-336e-49dc-b81c-5ffaa205d50c.png)

Screen sizes are default tailwind. 

Could be the Material Tailwind but I don't think so?

```
const withMT = require("@material-tailwind/react/utils/withMT");

/** @type {import('tailwindcss').Config} */
module.exports = withMT({
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {},
        screens: {
            'sm': '640px',
            // => @media (min-width: 640px) { ... }

            'md': '768px',
            // => @media (min-width: 768px) { ... }

            'lg': '1024px',
            // => @media (min-width: 1024px) { ... }

            'xl': '1280px',
            // => @media (min-width: 1280px) { ... }

            '2xl': '1536px',
            // => @media (min-width: 1536px) { ... }
        }
    },
    plugins: [
        require('tailwindcss-debug-screens'),
    ]
});
```

**Comment by jorenvanhee** [comment]
Looks like material-tailwind is indeed adding some [breakpoints](https://github.com/creativetimofficial/material-tailwind/blob/1a8738335c41c0a2065a6025cda85875bcdd24ad/packages/material-tailwind-react/src/theme/base/breakpoints.js). You can use the `ignore` option to stop `lg-max` from showing up.

https://github.com/jorenvanhee/tailwindcss-debug-screens#ignore-screens
