### ISSUE TITLE
Plugin seems to stop working around Tailwind 3.3.x

### ISSUE THREAD

**Issue by colinscz** [jorenvanhee/tailwindcss-debug-screens#18]
Hi @jorenvanhee 

The plugin seems to stop working around Tailwind version 3.3.x. Unfortunately I have no error log in the console as of now. I just can't seem to see the information in my bottom left of the browser anymore.

**Using:**

- Node 16.x
- TailwindCss 3.3.2
- Next.js 13.2.4
- Chrome Version 113.0.5672.127 (Official Build) (64-bit)

I will double check. This is just to raise awareness already.

Thanks for this plugin - it's really helpful during development!

Cheers

**Comment by jorenvanhee** [comment]
I just made a minimal tailwindcss setup with the plugin and I did not have any issues.

Could it be that your [content configuration](https://tailwindcss.com/docs/content-configuration) is not complete? The class "debug-screens" should be present in one of the files from the content paths.

If you can't seem to figure it out, feel free to make a minimal reproducible example. Thanks!

**Comment by colinscz** [comment]
@jorenvanhee I resolved it in the meantime, probably some misconfiguration on my side, content configuration was correct though. Thanks for investigating!
