### ISSUE TITLE
Doesn't support screens defined by min, max

### ISSUE THREAD

**Issue by dzcpy** [jorenvanhee/tailwindcss-debug-screens#20]
For example, this config is not supported:
```js
{
  sm: { min: '576px', max: '767px' }
}
```

**Comment by jorenvanhee** [comment]
I just tried it and [it works](https://play.tailwindcss.com/mhjTnVczMS?file=config). It's possible that one of your other breakpoints take precedence over `sm`. Can you please share an example with your complete config on [play.tailwindcss.com](https://play.tailwindcss.com)?
