### ISSUE TITLE
How to use debug-screens in React JS App

### ISSUE THREAD

**Issue by krayush1109** [jorenvanhee/tailwindcss-debug-screens#23]

**Comment by jorenvanhee** [comment]
Your react app will have a body tag defined somewhere. Just make sure the `debug-screens` class is present on the body tag during development. Depending on how you use React, you'll have a way to detect the environment. Maybe with something like this (not tested):

```jsx
<body className={process.env.NODE_ENV != 'production' ? 'debug-screens' : ''}>
```
