### ISSUE TITLE
alternate background color when switching between breakpoints

### ISSUE THREAD

**Issue by paulovieira** [jorenvanhee/tailwindcss-debug-screens#3]
Hello Joren, nice plugin, thanks for sharing!

I added a little feature for myself: when switching between breakpoints (from `sm` to `md`, for instance), the background color changes. 

The objective is just to call attention to that fact. Otherwise the change in breakpoints can be reached but it's easy to miss (because the eyes are not always looking at the bottom corner).

I can send a pull request if you are interested in this.

**Comment by jorenvanhee** [comment]
That's a good idea :) I'll try to add something with some kind of animation.

**Comment by jorenvanhee** [comment]
I played around with it and came up with this: https://objective-ramanujan-818c40.netlify.app/. Not too sure about it, but let me know what you think :)

**Comment by paulovieira** [comment]
Fantastic! It gives a really nice touch to this plugin, congratulations.

To make it even better I'd also switch the background color when changing breakpoints. I came up with this in my project:

```js
// tailwind.config.js

...

theme.debugScreens = {
  style: {
    fontSize: '14px',
    fontFamily: 'monospace',
    // ...
  },
  alternateBackgroundColor: defaultTheme.colors.indigo['700']  // new property
};
```

```js
  // index.js
  
  ...

  const alternateBackgroundColor = theme('debugScreens.alternateBackgroundColor');

  Object.entries(screens)
    .filter(([screen]) => !ignoredScreens.includes(screen))
    .forEach(([screen], idx) => {
      components[`@screen ${screen}`] = {
        '.debug-screens::before': {
          content: `'screen: ${screen}'`,

          // it's ok if alternateBackgroundColor is undefined (tailwind won't add it in that case)
          ...(idx % 2 === 0 ? { backgroundColor: alternateBackgroundColor } : {}),
          ...(idx % 2 === 1 ? { backgroundColor: components['.debug-screens::before'].backgroundColor } : {})
        },
      };
    });

  addComponents(components);
```

**Comment by jorenvanhee** [comment]
Hi, I appreciate your suggestion but I'll keep this out of the project. I want to keep it as low profile as possible and I personally wouldn't use this.
